apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-app-rules
  namespace: demo
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: flask-app.rules
    rules:
    - alert: FlaskAppHighRestartRate
      expr: increase(kube_pod_container_status_restarts_total{namespace="demo", pod=~"flask-app-.*"}[5m]) > 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Flask app containers restarting frequently"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} restarted more than once in the last 5 minutes."
