apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: demo
  labels:
    app: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000

